#+title: Han Characters
#+date: 2016-06-30

If you're learning a language using Han characters, and you haven't known Han characters already, start with just the phonetic alphabets first. If you know them already... maybe starting with just phonetic alphabets would also be a good idea, but the difference won't be that significent.

So, say if you're starting to learn Mandarin. You first learn the phonetic alphabet of choice (I'd advice Bopomofo since it's, I think, more optimized for Mandarin, but pinyin may feel more familiar), then just start learning it without thinking about Han characters.
After a while, when you have a basic set of vocabulary, start learning the Han characters - assigning these characters to the words. For example, after you've learned "zhuo zi5"(table), "yi3 zi5" (chair), and maybe when you can say something like "wo3 zhuo4 zai4 yi3 zi5 shang4, kang4 zhe5 yi4 zhang zhuo zi5" (I sit on a chair looking at a table), you start learning the Han character for wo3 (I): 我, zhuo (table): 桌, kang4 (look): 看, etc., eventually learning the whole sentence's Han characters. (我坐在椅子上看著一張桌子)

This is how I think Han characters work: they represent ideas, and are assigned to words for better clarification.

* Tags
[[file:opinions.org][Opinions]]
[[file:blog.org][Blog]]

* Language

[[file:language-english.org][English]]
