#+title: My list of notable anime series in 2017
#+date: 2017-12-31T23:59:57

2017 is the second year since I started following seasonal anime. (I started with Re:0 last summer.)

There have been a few series that I liked this year, and this is the list.

◊stylized-item{Saga of Tanya the Evil (Youjo Senki)} This is actually a story about an alternative version of World War I in a world with semi-magical powers.

When this series aired, I thought this is just another loli series that kind of just screws around. Then a few months after the broadcast, I decided to pick up this series after watching a review of it (and being spoiled) on Youtube. It was actually quite nice.

I wish I could see its actual ending though. That's the problem with adaptations…

◊stylized-item{Sakurada Reset} I love this series. Maybe it's because how I *somehow* relate to Haruki, maybe it's the English version that sucked… Fight me.

This is a story taking place in a superpower-filled town, about solving the mysteries two of the main cast face.

It's adapted into a movie (series) and an anime at the same time, but I've heard that the movie was heavily abridged… They really should have put the budget into the anime instead of the movie.

I do agree the animation leaves a lot to be desired though. There are way too many still frames, even when they could have at least added a little bit of wind or camera movements.

Oh, and Souma Sumire's voice is *so* great.

◊stylized-item{Sukasuka} Series like this are why I love fantasy stories. I just love daydreaming in those wonderfully constructed worlds. The world Sukasuka takes place in is one that's actually quite hopeless, even compared to our own. This is the *stomach aching* series of Spring 2017.

I really like how the animation is focused on Chtholly ◊rant{can never remember how her name's spelled…}, while the light novel focuses on Willem.

◊stylized-item{Made in Abyss} Colwelela (Hanezeve yulu-mai) kalalila!

◊rant{I'm two lines away from finishing making up the language of Hanezeve Caradhina, really should finish that soon…}

I used to dream about an abandoned house in a hazy forest, thinking about how nice it'd be to explore somewhere like that. This story gives me the same feeling.

With the second season announced (pretty sure it'll still be seasonal anime), I'm looking forward to following this series in 2018.

◊stylized-item{Fukumenkei Noise} This series aired while I was trying out practicing singing (which I currently put on hold), so it sort of grabbed my attention being a story around three people involved in music. ◊rant{I just noticed Yuzu goes by the same name as the protagonist in Citrus, how ◊s{wonderful}…}

Being a manga adaptation (that isn't extremely successful), the manga is where all the future updates will go. I do like how this story was set up, but hope that I could see more…

◊stylized-item{Konosuba S2} Being one of the more well made comedy series of recent time (?), Konosuba doesn't really *need* a second season to be an enjoyable ride, but this season lives up to its promise. It really is quite fun to watch.

That said, I personally still prefer deeper stories, with characters to relate to and relationships / motivations to figure out.

◊stylized-item{Kino's Journey (Kino no tabi)} Kino's Journey has always been its own weird beast that somehow works. The novel series has been going on for almost as long as I've lived…!

To be honest, the way the countries treat a traveller seems a bit unnatural to me… but that can easily be explained by how the countries are kind of just spread out everywhere. There might not be as many people travelling around like on earth.

I wouldn't go so far as to say I *love* this series, but it's certainly really confortable to watch (and read).

◊stylized-item{Girl's Last Tour (Shoujo Shuumatsu Ryokou)} Kino's Journey, Post-apocalyptic edition (?).

These two stories *kind of* work the same way, although Shuumatsu is focused much more on the interactions between the two protagonists. They both just kind of wander around into adventures, and don't really have a real goal (at least initially).

I particularly really like how the city Chito and Yuuri travels in is portrayed. By the way, an episode of ◊youtube["channel/UCZFipeZtQM5CKUjx6grh54g"]{“Science and Futurism with Isaac Arthur”} actually talked about a concept *probably physically possible* similar to this story's, that involves building ◊youtube["watch?v=ioKidcpkZN0"]{“Mega Earths”} with layers and layers of living space.

◊stylized-item{Houseki no Kuni} I originally started watching this series to see how a CG anime would look like, but as I watch it, I started to simply appreciate it regardless if it's CG or not.

Above that, I also like the story a lot. Phos is quite a lovable character, and shipping Shinsha and Phos is quite enjoyable.

I haven't seen any Buddhism-influenced stories in the past, so this one is quite refreshing to me.

◊stylized-item{Just Because} This is a steady love story with not-too-bad visuals. It's a light story compared to many other series, and is quite relatable as a third grader in high school.


Last year I didn't have the chance to follow anime every season, so this is a new one for me. I'm (mostly) looking forward to 2018. ◊rant{Except turning 18 soon...}

* Tags
[[site:anime.org]]
* Language
[[site:language-english.org][English]]
