#+title: As a Taiwanese, why do I prefer to use a Japanese name?
#+created: 2021-10-10T16:44:40+0900
#+updated: 2022-01-01T21:12:16+0900
#+tags[]: meta

I use a Japanese name despite being Taiwanese. When I introduce myself as Kisaragi in college, sometimes people mistaken me as being Japanese. I think I need to at least attempt to clarify this.

* Why foreign names are fine

Foreign names are common in Taiwan. Most people have an English name, even if their native language is Mandarin or something else. These names often bear zero semblance to our native names. When learning a new language, people also often adopt names in that language.

My eldest sister also has a Japanese name so I don't think this is a problem.

* Why I don't use my given name

My given name is very much a male name. As I'm trying to transition… it's just in the way.

My given name is also, with no disrespect to my parents, given with a questionable outlook of my life. I'll attempt to explain it here without actually revealing it:

- The first part seems to be the male version of my family's naming convention for my generation. However, the character has an extra /fire/ radical added because a fortune teller said my life lacked /fire/. Putting aside the unreliability of fortune tellers, I don't want more /fire/ in my life.
- The second part is just a generic character for boys born in years of dragon, such as the year 2000.

* Why “Kisaragi Hiu”

At first I just wanted a two-character name that I could use as an online handle, and I settled on 飛羽 in 2013, which I translated to /Flying Feather/ at the time. This is where my Twitter handle (@flyin1501) comes from.

Later I saw the word 如月 and thought sounded nice, so I added it to my handle. For a lack of a better idea, I used /Moonlight Feather/ as the English version of it. Meanwhile I continued to use a male English name given to me back in kindergarten, even though I hated it, because I fully understood that /Feather/ is not exactly an acceptable name.

I later learned that 如月 is an old East Asian name for February.

Eventually I realized there's actually an existing brand which is also called /Moonlight Feather/, which prompted me to finally figure out another English name. I didn't want to choose a random name like, say, /Alice/, that I felt no connections to, so I wanted to use a transcription of 如月飛羽 instead.

/Ru Yue Fei Yu/ felt too clunky, and turns out /Kisaragi Hiu/ actually does work as a Japanese name, so Kisaragi Hiu it is.

This is, to be honest, not necessarily more thought than what my parents had put into my given name. However, it at least reflects /my/ outlook on myself, instead of an expectation that doesn't serve me.
