#lang pollen
◊define-meta[title]{Iterations of Learning}
◊define-meta[date]{2017-10-10T00:00:00}
◊define-meta[category]{Opinions}
◊define-meta[language]{en}

Learning is based on iterations. Do something, then repeat, then repeat until you're familiar with it, is essentially the process; people call this "practice".

Different subjects have different sorts of steps to repeat, for instance:


◊h3{Language learning}

1. Find a unit of text (eg. a sentence).

2. Figure out what it means.

3. Repeat.

◊h3{Piano}

1. Find an unfamiliar sheet.

2. Divide it into smaller chunks.

3. Play each chunk until some level of familiarity.

4. Combine them together.

5. Repeat.

Learning is essentially finding the steps of an iteration, and then doing it again and again.
#+title: Iterations of Learning
#+date: 2017-10-10T00:00:00+0800
#+category: Opinions
#+language: en

Learning is based on iterations. Do something, then repeat, then repeat until you're familiar with it, is essentially the process; people call this "practice".

Different subjects have different sorts of steps to repeat, for instance:


- Language learning ::

  1. Find a unit of text (eg. a sentence).
  2. Figure out what it means.
  3. Repeat.

- Piano ::

  1. Find an unfamiliar sheet.
  2. Divide it into smaller chunks.
  3. Play each chunk until some level of familiarity.
  4. Combine them together.
  5. Repeat.

Learning is essentially finding the steps of an iteration, and then doing it again and again.
