#+title: Colwelelo Kalalila (Day 3, 4)
#+date: 2017-12-08T19:03:56+0900
#+category: Hanezeve Caradhina Language Construction
#+language: en

The last two days I listened to the song a few more times to check the lyrics, and then made up another line in section B.

Listen to Hanezeve Caradhina [[https://open.spotify.com/track/0KzOeB44GAj2rHmoXML0eb][on Spotify]].

* Lyrics changes

I found two parts that should be changed:

1. The word for "journey", "lalelila", sounds more like "walelila".
2. The first sentence of B and 'B should be the same.

◊hr[]

#+begin_src text
A.
Halalaha zela halalelu
Sivivile shi-dhina
◊span[#:style "color:red;"]{houwelela, lalelila}
◊span[#:style "color:green;"]{houwelela, walelila}
Hanezeve cara-dhina

B.
◊span[#:style "color:red;"]{Halalaha la forðe hala}
◊span[#:style "color:green;"]{Holo loholo forðe holo}
helelele lelele
...

'B.
◊span[#:style "color:red;"]{Kodo wodo hondo hondo-oh}
◊span[#:style "color:green;"]{Holo loholo forðe holo}
...
#+end_src

◊hr[]

* The lyrics, again

#+begin_quote
A.
Halalaha zela halalelu
Sivivile shi-dhina
houwelela, walelila
Hanezeve cara-dhina

B.
holo loholo forðe holo
helelele lelele
colwelela kalalila
Hanezeve yulumai ni

A.
Halalaha zela halalelu
Sivivile shi-dhina
houwelela, walelila
Hanezeve cara-dhina

'B.
holo loholo forðe holo
helelele lelele
colwelelo kalalila
Hanezeve yulumai ni

A.
Halalaha zela halalelu
Sivivile shi-dhina
houwelela, walelila
Hanezeve cara-dhina
#+end_quote

* Let's continue our journey

The A section is already done, now there's the rest of B.

Let me start with the line =colwelelo kalalila=. The word "kalalila" shares the "-lila" suffix with "walelila" (wonder), and it would make sense if it meant something like "journey", so I'll make it so. Now I can make up the meaning of "-lila" to be "unknown"; piecing these words together, I'll get:

- "-lila": "unknown"
- "wale-": "idea"
- "kala": something like "seeking"
- "walelila": "idea-unknown" = "wonder"
- "kalalila": "seeking-unknown" = "journey"

Now I'm not quite sure what I want the word "colwelela" to mean. Currently I'm thinking that it means "to start", but it's only one syllable away from "houwelela"... I'll ignore that similarity for now.

So "colwelela" can mean "start", and let's say "colwelelo" means "continue". This way, the lyrics can progress from "let the journey begin" to "let the journey continue", which somewhat fits the image of the song itself. I think that transition in the middle of the song really sounds like Riko's journey down to layer 2; considering it's also played when they leave layer 2, these points just kind of line up.

The word order here with "start journey" / "continue journey" is different than the first line, "dream I imagine". I'm putting this off as well, but maybe this can be how "let object action" is written...?

- "colwelela": "start"
- "colwelelo": "continue"
- "colwelela kalalila": "start (seeking-unknown = journey)"

* Walelila Halalelu

With this, we can transliterate most of the lyrics already:

#+begin_quote
A.
(thought-fiction = dream) I (thought-make = imagine)
explore even-deep
treasures, (idea-unknown = wonder)
Abyss in-deep

B.
???? ????
???? ????
start (seeking-unknown = journey)
Abyss at-bottom to
#+end_quote

And the translated lyrics is now:

#+begin_quote
A.
I am dreaming a dream
to explore even deeper
the treasures, the wonder
Deep in the Abyss

B.
Holo loholo forðe holo
Helelele lelele
Let the journey begin
to the bottom of the Abyss

A.
I am dreaming a dream
to explore even deeper
the treasures, the wonder
Deep in the Abyss

'B.
Holo loholo forðe holo
Helelele lelele
Let the journey continue
to the bottom of the Abyss

A.
I am dreaming a dream
to explore even deeper
the treasures, the wonder
Deep in the Abyss
#+end_quote
