#+title: Publishing my poems as a web-based book
#+date: 2019-12-16T19:48:23+0900
#+tags[]: Writing Pollen
#+language: en
#+category: Project announcements

I started writing poems (mostly in Mandarin) intermittently in 2013. Initially I put them on Blogger; I then moved them into this site in 2017. However, since they were quite different from everything else on this site (not to mention in a different language), and since I don't really have a category / tag system that works well, I effectively removed all mentions to them on this site. They were still hosted here, but there were no links in any of the main pages.

Last week I finally got around to doing something about it. I've [[https://barren-moon.kisaragi-hiu.com][packaged them into a poem collection]], although it's still in Mandarin only.

The book is built with Pollen, presented with CSS Grid, with the link style inspired by [[https://practicaltypography.com][Practical Typography]]. It should look fine on most screen sizes, +and I plan to make a PDF version to sell on [[https://booth.pm][Booth]].+

/2020-10-31T04:23:05+0900: I now think I should move on from it. The PDF version is probably not happening./
