#+title: 2020 review
#+date: 2020-12-17T03:32:42+0900
#+tags[]: Org UTAU Emacs Trumpet
#+category: Yearly reviews
#+toc: #t

Last year I saw [[https://www.taniarascia.com/2019-into-2020/][Tania Rascia’s 2019 into 2020]] article and thought I should do the same, but I procrastinated so much that now I’m writing a review for 2020 instead of 2019.

* Articles

I wrote way too few articles this year. I’ve been keeping more private notes, some of which are more suited to this blog, so I’ll probably publish more next year.

- [[file:2020-10-31-current-infrastructure.org][Current infrastructure of this site]]
- [[file:2020-10-25-ox-pollen.org][ox-pollen announcement]]
- [[file:2020-02-16-slack-export-to-org.org][Exporting my Slack data to an Org mode file]]

* Projects
** org-roam pull requests

I started learning about Zettlekasten in June, and started using [[https://www.orgroam.com/][Org-roam]] in August after dabbling with my own implementation of backlinks for a bit. Now when I add new diary entries, I no longer have to worry about not being able to recall old entries: backlinks and index notes allow me to see related notes easily.

As I switched to it, there were some ideas that I was able to implement, open a pull request, and got accepted.

Roughly sorted by amount of effort.

- =org-roam-file-exclude-regexp= ([[https://github.com/org-roam/org-roam/pull/1046][1046]])
- minor bug fixes ([[https://github.com/org-roam/org-roam/pull/1081][1081]], [[https://github.com/org-roam/org-roam/pull/1220][1220]])
- documentation ([[https://github.com/org-roam/org-roam/pull/1251][1251]], [[https://github.com/org-roam/org-roam/pull/1253][1253]])
- preserve existing description when replacing a =roam:= link ([[https://github.com/org-roam/org-roam/pull/1327][1327]])
- removing file-truename resolution ([[https://github.com/org-roam/org-roam/pull/1109][1109]])
- multiple =roam_key= statements ([[https://github.com/org-roam/org-roam/pull/1215][1215]])

** UTAU covers

I also made way too few covers this year. There are at least two covers that are really close to complete but I’ve just been putting aside “for now”.

- 2020-10-24: 秘密 - はるまきごはん / 雨月 ([[https://nicovideo.jp/watch/sm37715002][niconico]], [[https://youtu.be/XTjMcCGgh6U][YouTube]])
- 2020-05-21: LEO - Eve / 闇音レンリ ([[https://nicovideo.jp/watch/sm36898552][niconico]], [[https://youtu.be/EI_97t8_i7o][YouTube]])
- 2020-01-22: ヨミクダリの灯 - シャノン / 闇音レンリ ([[https://nicovideo.jp/watch/sm36261157][niconico]], [[https://youtu.be/VZAbZQkCT3M][YouTube]])

** new Emacs packages

- [[file:../projects/ox-pollen.org][ox-pollen]]
- +kisaragi-hydration+ → [[https://gitlab.com/kisaragi-hiu/kisaragi-log][kisaragi-log]]
- [[https://gitlab.com/kisaragi-hiu/dired-show-readme][dired-show-readme]]

* Learning
- I started taking classes in illustration and animation, although I haven’t been practicing enough.
- I started learning German in university, although
- I entered the wind band club in college (2020-03-17), trying (and struggling) to learn the trumpet.
