#+title: 「一行字」並不比「一列字」來的沒有道理
#+subtitle: 要用「一列字」沒關係，但請不要將「一行字」視為錯誤
#+created: 2026-08-02T19:11:25+0900
#+tags[]: Opinions
#+series: Translation discourse
#+language: zh_TW

行列原本是表格、直書方塊字文章等等的用詞，橫的是列，直的是行。二十世紀左右漢字文化圈各語言開始用橫書之後，「一行字」在橫書的時候變成橫的。有些人覺得因為橫的是列，直的是行，因此橫書的時候應該稱作「一列字」。

我不會說用「一列字」是錯的，自己要如何書寫並不需要每個人都追隨完全相同的標準。但「一行字」也不是錯的。

第零，語言就是「將錯就錯」，規則也是人選的，並不會比大部分話者所接受的來的正確。

第一，「一行字」代表的是一小段文字，為了排版而將一串文字切斷成多個單位的這些單位。文字「行」是「一小段文字」而不是「排列的事物中直列者」。

第二，（這也是第一點的證據），[[https://en.wiktionary.org/wiki/%ED%96%89#Korean][整個]] [[https://www.weblio.jp/content/%E8%A1%8C][漢字]] [[https://en.wiktionary.org/wiki/%E8%A1%8C#Vietnamese][文化]] [[https://en.wiktionary.org/wiki/%E8%A1%8C#Pronunciation_2][圈]] 都有選擇用「行」來代表橫書的一小段文字。

第三，「行代表一小段文字」並不比「行是直的所以橫書應該講列」來的沒有道理。它們同樣是人所決定的。

最後我想要給一個例子。台灣的書的書寫方向，直書橫書都有，我們會讀了之後其實不太需要意識到或是記住自己在讀的書到底是直書還是橫書，就好像大部分人也不會記住一本書是用黑體還是明體一樣。我今天如果要詢問某個名字出現在哪一本書哪一頁的哪一 *行* ，這個行字代表的是什麼？一小段文字。如果有些書直寫有些書橫寫，當我問行的時候我是在問當表格看的行列嗎？不是。

如果要把橫的文字行一律叫做列，這裡能怎麽做？

- 「哪一行/列」行不通。我並沒有要問直書的垂直位置（視為表格時的列）或是橫書的水平位置（視為表格時的行）。
- 「哪一行（如果是直書的話）還是哪一列（如果是橫書的話）」邏輯上正確但聽起來並不自然。用豪華一點的說法，這樣講的[[https://en.wikipedia.org/wiki/Register_(sociolinguistics)][語域]]並不正確。

我希望這個例子足夠說明為什麼將橫書文字行視為錯誤用法是行不通的事情。文字要用列沒關係，但請不要把行視為錯誤。

* Practical use

基本上因為讀者並不可能避免同時接觸到 zh_CN 與 zh_TW、也因為 zh_CN 和 zh_TW 的行列定義完全相反，所以我在翻譯 row/column 時基本上是避免用 row = 列 column = 行，而是用 row = 列 column = 欄。至於純文字編輯器會看到的 line/column，這同樣是把表格的邏輯套用到文字上面。雖然橫書的文字行因為是橫書所以是橫的，但在這裡用行列的話一樣會容易混淆（光日文跟 zh_CN 的行列都跟 zh_TW 相反這件事情就會混淆了）。用「欄」一樣可以解決這個問題。

所以：row = 列, column = 欄, (text) line = （文字）行。
