#+title: As a Taiwanese, why do I use a Japanese name?
#+created: 2021-10-10T16:44:40+0900
#+tags[]: meta

I use a Japanese name despite being Taiwanese. When I introduce myself as Kisaragi in college, sometimes people mistaken me as being Japanese. I think I need to at least attempt to clarify this.

* Why foreign names are fine

- Foreign names (that bear zero resemblance to our names given at birth) are commonplace in Taiwan. It is also not uncommon for people to adopt a new name in the language that they are learning.
- I also see my sister using a Japanese name in Japan; that name bears no resemblance to her Mandarin name, and serves as her legal name in Japan regardless.

* Why I don't use my given name

- It's a male name. I'm very much in the (very slow) process of transitioning, so… no.
- With no disrespect to my parents, it was named with little thought, and it's based on a questionable outlook. I'll attempt to explain it here without actually revealing it:
  - The first character is just my family name, there's no issues here.
  - The second character seems to be the male version of my family's naming convention for my generation. BUT! From what I remember having heard from my parents, because a fortune teller told them my life lacks /fire/, the character has a fire radical slapped onto it. This turns the character into one that refers to sunshine — even within the fortune teller's framework, surely you shouldn't slap a whole star's worth of /fire/ onto somebody's life because they lack it?
  - The third character is a generic character for boys born in years of dragon (which the year 2000 was one).

* Why “Kisaragi Hiu”

- At first I just wanted a two-character name that I could use as an online handle, and I settled on 飛羽 in 2013, which I translated to /Flying Feather/ at the time. This is where my Twitter handle (@flyin1501) comes from.
- I saw the word 如月 the next year, which I thought sounded nice, so I added it to my handle. For a lack of a better idea, I used /Moonlight Feather/ as the English version of it. Meanwhile I continued to use a male English name given to me back in kindergarten, even though I hated it, because I fully understood that /Feather/ is not exactly an acceptable name.
  - I later learned that 如月 is an old East Asian name for February.
- Eventually I realized there's actually an existing brand which is also called /Moonlight Feather/, which prompted me to finally figure out another English name.
  - I didn't want to choose a random name like, say, /Alice/, that I felt no connections to, so I wanted to use a transcription of 如月飛羽 instead.
  - /Ru Yue Fei Yu/ felt too clunky, and turns out /Kisaragi Hiu/ actually does work as a Japanese name, so Kisaragi Hiu it is.

This is, to be honest, not necessarily more thought than what my parents had put into my given name. However, it at least reflects /my/ outlook on myself, instead of an expectation that doesn't serve me.
