#+title: Projects
#+hugo_nolist: true
#+toc: true

A list of my projects.

Incomplete: illustrations on Pixiv, other things that I've forgot, etc. still need to be added..

* → [[file:../covers.html][UTAU Covers]]
* → Illustrations (TODO)

* Coding
** Emacs

{{% project "https://kisaragi-hiu.com/" "yaml.el" %}}
Work in progress: eventually might become a YAML library in pure Emacs Lisp.
{{% /project %}}

{{% project "https://gitlab.com/kisaragi-hiu/tst.el" "tst.el" %}}
An Emacs Lisp library implementing a syntax for specifying tags inspired by TagSpaces.
{{% /project %}}

{{% project "https://github.com/kisaragi-hiu/background-job.el" "background-job.el" %}}
An Emacs Lisp library to start jobs in the background that try not to block the user too much.
{{% /project %}}

{{% project "/projects/ox-pollen.html" "ox-pollen" %}}
Org to Pollen exporter.
{{% /project %}}

{{% project "https://gitlab.com/kisaragi-hiu/kisaragi-log" "kisaragi-log" %}}
Tracking amounts of stuff in Emacs. Supercedes kisaragi-hydration because I wanted to track more than just water intake.
{{% /project %}}

{{% project "https://gitlab.com/kisaragi-hiu/kisaragi-hydration" "kisaragi-hydration" %}}
My own hydration tracker. Superceded by kisaragi-log.
{{% /project %}}

{{% project "/projects/ust-mode.html" "UST mode" %}}
Major mode for UTAU project (UST) files.
{{% /project %}}

{{% project url="https://gitlab.com/kisaragi-hiu/didyoumean.el" title="DidYouMean.el" melpa-badge="didyoumean" %}}

Ask for the right file to open.

Emacs port of the [[https://github.com/EinfachToll/DidYouMean][DidYouMean]] Vim plugin.
{{% /project %}}

{{% project "https://gitlab.com/kisaragi-hiu/dired-show-readme" "dired-show-readme" %}}
Dired extension to show README of current directory.
{{% /project %}}

{{% project url="https://github.com/kisaragi-hiu/cangjie.el" title="Cangjie.el" melpa-badge="cangjie" %}}
Retrieve Cangjie code for Han character in Emacs.

This is my first Emacs package.
{{% /project %}}

{{% project "/projects/canrylog.html" "Canrylog" %}}
An experimental time tracking application.
{{% /project %}}

{{% project "https://git.sr.ht/~kisaragi_hiu/yasearch" "yasearch" %}}
Yet Another web Search plugin for Emacs.

Search the word under point or region on the web.
{{% /project %}}

{{% project "/projects/org-msr.html" "org-msr" %}}
My personal spaced repetition system, implemented with Org-mode repeaters.
{{% /project %}}

** Web / Design

{{% project "https://github.com/kisaragi-hiu/kisaragi-hiu.com" "kisaragi-hiu.com" %}}
This site. Built on Pollen and Racket, using a minimal style, and spamming purple everywhere.
{{% /project %}}

{{% project "https://gitlab.com/kisaragi-hiu/barren-moon" "如同月球般的荒涼(Barren Moon)" %}}
A web-based book. Collection of poems I wrote in junior and senior high school.
{{% /project %}}

** Commands

{{% project "https://github.com/kisaragi-hiu/bk" "bk" %}}
Key-value pair storage based on JSON, intended for command line bookmarks.
{{% /project %}}

{{% project "https://github.com/kisaragi-hiu/randomwallpaper" "randomwallpaper" %}}
A script to set a random wallpaper from a directory every so often.
{{% /project %}}

** Other

{{% project "https://gitlab.com/kisaragi-hiu/language-startup-benchmark" "Language Startup Benchmark" %}}
Time hello world in various languages to benchmark their startup times.
{{% /project %}}

* osu! Skins & related

{{% project "https://github.com/kisaragi-hiu/osuskin-retome" "Retome" %}}
My personal osu! skin, focused on glow and shadow effects.
{{% /project %}}

{{% project "https://github.com/kisaragi-hiu/font-rozerofo" "Rozerofo" %}}
A font for the /Romoji/ script from [[https://en.wikipedia.org/wiki/Re:Zero_−_Starting_Life_in_Another_World][Re:Zero]].
{{% /project %}}
