#+title: org-msr
#+github: https://github.com/kisaragi-hiu/org-msr
#+gitlab: https://gitlab.com/kisaragi-hiu/org-msr
#+tags[]: org-mode
#+status: done
#+created: 2019-05-03T17:57:22+0900

My personal spaced repetition system, implemented with Org-mode repeaters.

Org-msr is a minimal spaced repetition setup for Org mode.

After years of usage, I don’t actually think this has been a good idea. Nevertheless, as my vocabulary collection uses it, I’m still not moving away.

* Usage

Run =org-msr-setup= in a Org mode file to

- add file TODO keywords according to =org-msr-keyword-frequency-alist=
- start =org-msr-mode= automatically when visiting this file.

Now for each heading you want to remember, run =org-todo= and select how frequently you want to see it. A repeater will automatically be added and updated, and you can see all items in your org-agenda.

I recommend using [[https://github.com/alphapapa/org-super-agenda][org-super-agenda]] and a [[https://orgmode.org/manual/In_002dbuffer-settings.html][filetag]] so that the =org-msr= entries don’t bury everything else in the agenda.

In your init:
#+begin_src elisp
(setq org-super-agenda-groups '((:name "Vocabulary"
                                       :tag "org-msr"
                                       :order 100)))
#+end_src

In the Org file:
#+begin_src org
,#+FILETAGS: :org-msr:
#+end_src
