name: Deploy

on:
  push:
    branch:
      - source
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  "build":
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          ssh-key: ${{ secrets.SSH_KEY }}
          ssh-known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      # - uses: pnpm/action-setup@v2
      #   with:
      #     version: 8
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
      - name: Create Vercel config
        run: |
          make vercel.json
      - name: Build and deploy
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        # GitHub preinstalls it.
        run: |
          vercel pull --yes --environment production --token ${{ secrets.VERCEL_TOKEN }}
          vercel build --prod --token ${{ secrets.VERCEL_TOKEN }}
          vercel deploy --prebuilt --prod --token ${{ secrets.VERCEL_TOKEN }}
